[general]
import = ["~/.config/alacritty/themes/molokai_dark.toml"]

[cursor]
style = "Block"
unfocused_hollow = true

[font]
size = 13.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Command"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Right"

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|\"' ()[]{}<>"

[window.dimensions]
columns = 80
lines = 100

[window.padding]
x = 5
y = 5

[window.position]
x = 0
y = 0
