
source $HOME/.config/vim/vim_defaults.vim

" My edits

set expandtab
set shiftwidth=4 "this is the level of autoindent
set softtabstop=4
set tabstop=4
set number
set relativenumber
set wildmenu
set showmatch
set is
set ic
syntax enable

" vim rgb-color-chart
" https://www.calmar.ws/vim/256-xterm-24bit-rgb-color-chart.html

" to create swap files in different directory
set directory=$HOME/.vim/.swapfiles/

set cursorline
hi CursorLine cterm=none ctermbg=235 ctermfg=none

set cursorcolumn
hi CursorColumn cterm=none ctermbg=235 ctermfg=none

hi LineNr cterm=none ctermbg=none ctermfg=cyan

" pop-menu
hi Pmenu cterm=none ctermbg=238 ctermfg=none

set laststatus=2
" hi StatusLine cterm=none ctermbg=236 ctermfg=cyan

" SearchResult
hi Search ctermfg=black ctermbg=229 cterm=none

" Vertical split separator
hi VertSplit cterm=none ctermbg=236 ctermfg=cyan

if &diff
    hi DiffAdd    cterm=none ctermbg=blue ctermfg=white
    hi DiffDelete cterm=none ctermbg=blue ctermfg=white
    hi DiffChange cterm=none ctermbg=blue ctermfg=white
    hi DiffText   cterm=none ctermbg=red  ctermfg=black
endif

command! Rts :%s/\s\+$//

set matchpairs+=<:>

source $HOME/.config/vim/mappings.vim

source $HOME/.config/vim/plugins.vim

source $HOME/.config/vim/coc_settings.vim

source $HOME/.config/vim/rust_settings.vim

source $HOME/.config/vim/fzf_settings.vim

