# C parser in Python
brew "pycparser"
# C Foreign Function Interface for Python
brew "cffi"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Automate deployment, configuration, and upgrading
brew "ansible"
# Codec library for encoding and decoding AV1 video streams
brew "aom"
# Record and share terminal sessions
brew "asciinema"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Core application library for C
brew "glib"
# Vector graphics library with cross-device output support
brew "cairo"
# OpenType text shaping engine
brew "harfbuzz"
# Google's own build tool
brew "bazel"
# GNU binary tools for native development
brew "binutils"
# Get/set bluetooth power and discoverable state
brew "blueutil"
# Collection of portable C++ source libraries
brew "boost"
# Emacs dependency management
brew "cask"
# Cross-platform make
brew "cmake"
# Tool for browsing source code
brew "cscope"
# Reimplementation of ctags(1)
brew "ctags"
# More intuitive version of du in rust
brew "dust"
# Simple, fast and user-friendly alternative to find
brew "fd"
# User-friendly command-line shell for UNIX-like operating systems
brew "fish"
# Command-line fuzzy finder written in Go
brew "fzf"
# GNU compiler collection
brew "gcc"
# GNU debugger
brew "gdb"
# Toolkit for image loading and pixel buffer manipulation
brew "gdk-pixbuf"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# Generate introspection data for GObject libraries
brew "gobject-introspection"
# Colorize logfiles and command output
brew "grc"
# Improved top (interactive process viewer)
brew "htop"
# CLI wrapper for basic network utilities on macOS - ip command
brew "iproute2mac"
# New file format for still image compression
brew "jpeg-xl"
# Framework for layout and rendering of i18n text
brew "pango"
# Library to render SVG files using Cairo
brew "librsvg"
# Just-In-Time Compiler (JIT) for the Lua programming language
brew "luajit"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Small build system for use with gyp or CMake
brew "ninja"
# Open-source, cross-platform JavaScript runtime environment
brew "node", link: false
# Swiss-army knife of markup format conversion
brew "pandoc"
# Interpreted, interactive, object-oriented programming language
brew "python@3.10"
# Pure Python Vim clone
brew "pyvim"
# Tools for and transforming and inspecting PDF files
brew "qpdf"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Version control system designed to be a better CVS
brew "subversion"
# OCR (Optical Character Recognition) engine
brew "tesseract"
# Terminal multiplexer
brew "tmux"
# Extremely fast Python package installer and resolver, written in Rust
brew "uv"
# Vi 'workalike' with many additional features
brew "vim"
# Executes a program periodically, showing output fullscreen
brew "watch"
# Password manager
cask "1password@nightly"
# Compact TeX distribution as alternative to the full TeX Live / MacTeX
cask "basictex"
# Web browser focusing on privacy
cask "brave-browser"
# E-books management software
cask "calibre"
cask "font-fira-code"
cask "font-fira-mono"
cask "font-fira-sans"
# ZSA keyboard firmware flasher
cask "keymapp"
# Media key forwarder for Apple Music and Spotify
cask "macmediakeyforwarder"
# Window manager
cask "tiles"
